	$(document).ready(function(){
			$('.article').load('info.html');
	});
	$(document).ready(function(){
		$('#div-li-myCalendar').click(function(){
			$('.article').load('myCalendar.html');
		});
	});
	$(document).ready(function(){
		$('#div-li-search').click(function(){
			$('.article').load('search.html');
		});
	});
  $(document).ready(function(){
		$('#div-li-setting').click(function(){
			$('.article').load('setting.html');
		});
	});
